FREQUENCIES sexe
frequence age

DATASET ACTIVATE DataSet0.
FREQUENCIES VARIABLES=age
  /NTILES=4
  /PERCENTILES=30.0 50.0 
  /STATISTICS=STDDEV VARIANCE MINIMUM MAXIMUM MEAN MEDIAN MODE SUM SKEWNESS SESKEW KURTOSIS SEKURT
  /ORDER=ANALYSIS.

DESCRIPTIVES VARIABLES=age
  /STATISTICS=MEAN STDDEV MIN MAX.

CROSSTABS
  /TABLES=situation BY sexe
  /FORMAT=AVALUE TABLES
  /STATISTICS=CHISQ 
  /CELLS=COUNT ROW COLUMN TOTAL 
  /COUNT ROUND CELL.
